WIP: payments history table
beabee-communityrm/beabee-frontend pull request #113
Opened 2022-02-24 14:14 UTC by basilesimon

2022-03-01 14:03 UTC, basilesimon commented
![Screen Shot 2022-03-01 at 14 56 13](https://user-images.githubusercontent.com/5701152/156182211-901fa38d-6fcc-457c-a093-847bce68df7e.png)
![Screen Shot 2022-03-01 at 14 56 18](https://user-images.githubusercontent.com/5701152/156182221-bb2551e6-3f1a-4918-acec-4ad3b02ed137.png)
![Screen Shot 2022-03-01 at 14 56 46](https://user-images.githubusercontent.com/5701152/156182226-85825af1-85eb-4e29-8542-72fa7840b67a.png)

2022-03-01 14:35 UTC, wpf500 requested changes
Nice one :+1:, just that one string to localise

2022-03-01 14:35 UTC, wpf500 commented on src/modules/contribution/components/PaymentsHistory.vue
> +    <SectionTitle class="mb-2">Payment history </SectionTitle>
Needs to be localised

2022-03-01 15:27 UTC, basilesimon commented on src/modules/contribution/components/PaymentsHistory.vue
> +    <SectionTitle class="mb-2">Payment history </SectionTitle>
nice one thanks

2022-03-03 15:52 UTC, aiscarvalho commented
Nice work! Things we noticed:
- the amount value, in the payment table, is too boldy. It is set in font-weight 900 and should be 700
- could we set a minimum table height of 12 rows (=12 payments) to avoid the jumpy pagination?
- pagination is missing the hover -- this is a general one, so maybe we add an issue to cover it?

We had a look but didn't quite understand what you meant by "favouring consistency" in the table. We can chat through it next week to better understand your vision :)

It's perfectly fine that we pick the select later. We can take some time to flesh out how the select and the pagination interact with each other, that isn't so clear atm.

2022-03-04 10:31 UTC, basilesimon commented
Addressed all concerns above!

https://user-images.githubusercontent.com/5701152/156747173-9b656150-d226-450c-a9a9-c2e7dbdabe2b.mov

2022-03-04 10:38 UTC, merged