feat: add empty slot to AppTable, WIP contact list messages
beabee-communityrm/beabee-frontend pull request #189
Opened 2022-05-12 10:53 UTC by rlafuente

Very much work-in-progress and not working yet, but I need some feedback on implementation details and a PR seems a good way to track those.

The main issue I need guidance with: when using search to filter the contact list, cases where there's no results should pop a specific empty message ("No results found"). We also want to accomodate a different empty message for when there's no contacts present at all.

However, I can't find a variable or state to make a condition against, to determine whether I'm running into an empty state because of a search with 0 results, or because there are no contacts at all. I just need that tidbit to be able to set a proper condition and take care of the other chores (e.g. mark strings as translatable)

(There already is a "no results found" message on the items count area, but it'd be preferable for it to appear in the table itself)

2022-05-17 10:05 UTC, rlafuente commented
Some good progress, updated the initial comment since it's apparently fixed

2022-05-17 14:02 UTC, rlafuente commented
I think the only remaining table to improve is the Callout archive, which is using a simple `<table>` instead of the AppTable component. It's doable but would break the DRY principle.

I can go ahead and try to port this table to AppTable so that it can work with empty sets, but would like assurance that this is the way to go :)

2022-05-18 13:34 UTC, wpf500 requested changes

2022-05-18 13:34 UTC, wpf500 commented on src/modules/contacts/ContactsPage.vue
> +          <p>{{ t('contacts.noResults') }}</p>
This could be simplified into one slot with the query inline which would be slightly better in terms of not repeating the slot.

```vue
<template #empty>
  <p>{{ route.query.s ? t('contacts.noResults') : t('contacts.noContacts') }}</p>
</template>
```

2022-05-18 13:39 UTC, wpf500 commented
> I think the only remaining table to improve is the Callout archive, which is using a simple `<table>` instead of the AppTable component. It's doable but would break the DRY principle.
> 
> I can go ahead and try to port this table to AppTable so that it can work with empty sets, but would like assurance that this is the way to go :)

Hmm if I remember correctly the styling of that table is different to other tables? I think its a good idea to use the `AppTable` component but I think this should be an opportunity to unify the styles rather than making the `AppTable` support lots of styles? What do you think? Possibly we could add a `loose` style to support the padding differences between the two?

2022-05-18 15:06 UTC, rlafuente commented on src/modules/contacts/ContactsPage.vue
> +          <p>{{ t('contacts.noResults') }}</p>
ah, elegant! Fixed in 38c4989fe8dbb749e294fa537d675c4992a2631c

2022-05-18 16:25 UTC, rlafuente commented
Def, now's always the best time for quick refactor wins :) Just pushed a first working version of the AppTable on the callout page. I still want to review and compare side-by-side with the previous version tomorrow.

2022-05-19 09:37 UTC, rlafuente commented
Okay, so the new callout AppTable seems to work just like the previous one, it's ready for review :rocket: 

(in the meantime, I changed the default empty message to a "Loading" message since it can flash for a bit while a page is loading. We should later test the UX more closely on this to be sure that these messages come out as expected)

2022-05-19 13:20 UTC, wpf500 commented
I think we ultimately need to differentiate between loading and no results, probably by `items` being nullable, but we can push this to another PR as this is an improvement on what came before.

2022-05-19 13:20 UTC, wpf500 commented on src/modules/contacts/ContactsPage.vue
> +          <!-- <i18n-t v-else keypath="contacts.noResults" /> -->
I guess this should just be removed now?

2022-05-19 13:20 UTC, wpf500 approved these changes

2022-05-19 15:24 UTC, rlafuente commented on src/modules/contacts/ContactsPage.vue
> +          <!-- <i18n-t v-else keypath="contacts.noResults" /> -->
oof, definitely. Thanks for catching that one (fixed in 8d4eda5)

2022-05-19 15:27 UTC, merged