Feat/share callout
beabee-communityrm/beabee-frontend pull request #212
Opened 2022-06-22 11:32 UTC by rlafuente

Now implemented with proper sharing links (only email missing, but posting the PR for review of the rest)

2022-06-23 15:39 UTC, wpf500 requested changes
Nice one! A few small changes requested but looks great :)

2022-06-23 15:39 UTC, wpf500 commented on src/modules/callouts/components/CalloutSharingPanel.vue
> +    Share this callout with the following address:
Needs to be localised

2022-06-23 15:39 UTC, wpf500 commented on src/modules/callouts/components/CalloutSharingPanel.vue
> +    Or quickly share using one of these services:
Needs to be localised

2022-06-23 15:39 UTC, wpf500 commented on src/modules/callouts/components/CalloutSharingPanel.vue
> +          E-mail
Needs to be localised

2022-06-23 15:39 UTC, wpf500 commented on src/modules/callouts/components/CalloutSharingPanel.vue
> +const calloutUrl = `${baseUrl}/${props.slug}`;
I think this should be:
```ts
const calloutUrl = `${baseUrl}/callouts/${props.slug}`
```

2022-06-23 17:32 UTC, rlafuente commented
Updated!

2022-06-29 08:24 UTC, wpf500 approved these changes

2022-06-29 08:24 UTC, merged