Tabbed UI for membership builder
beabee-communityrm/beabee-frontend pull request #326
Opened 2022-12-07 11:48 UTC by rlafuente

Some UX details missing:

- [ ] include a confirmation hint when update is finished
- [ ] review padding for Submit buttons
- [ ] the first tab should be open by default when opening the membership builder

Otherwise, the feature should be working as expected.

![image](https://user-images.githubusercontent.com/159868/206170340-8c7e83cc-c15f-4e95-9f13-c9ff4a4cd7de.png)

2022-12-07 14:37 UTC, wpf500 commented
Just a quick FYI: you should be able to use `AppForm` to handle all the loading/confirmation/error states of the update

2022-12-08 15:06 UTC, wpf500 requested changes
Good stuff! Just needs a couple of changes and to fix merge conflicts then good to go

2022-12-08 15:06 UTC, wpf500 commented on src/pages/admin/membership-builder.vue
> +    to: `/admin/membership-builder/join-form`,
Incorrect `to`, gives not found

2022-12-08 15:06 UTC, wpf500 commented on src/pages/admin/membership-builder/index.vue
> -import { MembershipBuilderEmitter } from '../../../components/pages/admin/membership-builder/membership-builder.interface';
Can you delete this now very happily unused file (membership-builder.interface)?

2022-12-08 15:20 UTC, wpf500 commented on src/pages/admin/membership-builder.vue
> +  <PageTitle :title="t('membershipBuilder.title')" border />
As per the design spec, page titles with horizontal tabs don't have a border. You can remove `border` attribute :)

2022-12-08 16:06 UTC, rlafuente commented
Done!

2022-12-08 18:15 UTC, wpf500 approved these changes

2022-12-08 18:15 UTC, merged