Callout map: Add New review
beabee-communityrm/beabee-frontend pull request #546
Opened 2024-02-22 13:56 UTC by rlafuente

**Note:** we're still missing the mobile UI for this, but it's good for testing on desktop

- update Add New button placement
- Cancel option when picking a point on the map
- Add New button included in the gallery, which switches back into the map view and starts Add New mode
- use query parameters to remove intro loading, needed for switching between map and gallery **(is this the best way?)**
- use the `callout.addNew` existing i18n key

2024-02-27 15:54 UTC, aiscarvalho commented
We've just updated the branch with the mobile Ui featuring the "Add new location" button in a bottom bar.
The bottom bar is visible if the map is embed. We figured this made sense because the "Add new" is placed there but we wanted to double check with you.

The "Add new" button is centred since, for now, it's the only element displayed in the bottom bar.

Screenshot of the mobile UI and spec for reference:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/69c95fb6-3cf4-4c5c-a70d-46b698c8dbb6)


![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/d7bf6472-be2e-4305-b722-45a53fc4004d)

2024-03-20 13:18 UTC, wpf500 requested changes
A couple of bugs too:

Double image on mobile
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/38b2b095-59f8-4bf7-886a-6a3950514bde)

Style problems between gallery and map:
[Screencast from 20-03-24 13:17:31.webm](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/81f084f8-aeca-4b8f-9427-6457e854dd40)

2024-03-20 13:18 UTC, wpf500 commented on src/pages/callouts/[id]/map.vue
>        <button
This could now be an `AppButton` like the other examples so the styles are shared

2024-03-20 13:19 UTC, wpf500 commented
Thanks for doing this so quickly, just a couple of little things to fix

2024-03-20 14:24 UTC, rlafuente commented
Okay just pushed the fixes; one outstanding detail is that the Add button disappears when viewing the gallery on mobile. I can look closer into this tomorrow.

2024-03-20 17:03 UTC, wpf500 approved these changes

2024-03-20 17:08 UTC, merged