Feat: Add paypal payment method
beabee-communityrm/beabee-frontend pull request #562
Opened 2024-03-26 16:47 UTC by JumpLink

* Add PayPal icon
* Add PayPal translations

Related:
* https://github.com/beabee-communityrm/beabee/pull/384
* https://github.com/beabee-communityrm/beabee-common/pull/14

2024-04-03 09:16 UTC, wpf500 commented
Looks good so far. I think you will also need to update the `PaymentSource` component, which shows the user their current payment source on their contribution page. It should reflect the PayPal payment source you added to the backend

2024-04-03 09:17 UTC, wpf500 requested changes
Looks good so far. You will also need to update the `PaymentSource` component, which shows the user their current payment source on their contribution page. It should reflect the PayPal payment source you added to the backend

2024-04-03 20:30 UTC, JumpLink commented
@wpf500 I have now moved `PaymentSource` to common because it's used from the frontend and the backend. For this, both projects must now use the same common version, so I have also updated the frontend to `0.20.3-alpha.2`. There were a few places where typescript complained about the types, so I didn't invest too much time in that and made it easy for myself with the types for now

2024-04-04 10:25 UTC, wpf500 reviewed
Good stuff. Just need to update the beabee-common version number once you've released v0.20.3 then this is good to go

2024-04-04 10:25 UTC, wpf500 commented on src/type/contribution-info.ts
> +import type {} from '@type';
Delete this line

2024-04-04 10:25 UTC, wpf500 approved these changes

2024-04-04 11:36 UTC, merged