feat(tax-rate): Add tax rate to membership builder
beabee-communityrm/beabee-frontend pull request #575
Opened 2024-04-16 14:31 UTC by JumpLink

Backend: https://github.com/beabee-communityrm/beabee/pull/397

2024-04-19 08:29 UTC, wpf500 requested changes
Can you move the tax rate setting from the membership builder into the settings? It can just go here under a new heading ("Payment"?)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/758c3a51-53ed-4e98-abf5-3c3cd4c132f6)

2024-04-19 09:02 UTC, JumpLink commented
> Can you move the tax rate setting from the membership builder into the settings? It can just go here under a new heading ("Payment"?)

sure

2024-04-19 18:07 UTC, JumpLink commented
@wpf500 I have moved the tax settings to the general settings page [on this branch](https://github.com/beabee-communityrm/beabee-frontend/pull/579). I think now the data should also be stored there in the database and no longer in join content, or what do you think?

2024-04-24 12:40 UTC, wpf500 reviewed
I think this PR doesn't add the tax rate to the join form right? Just the admin side?

2024-04-24 12:40 UTC, wpf500 commented on src/pages/admin/settings/index.vue
> +                :min="1"
I think 0% could be a legit tax rate

2024-04-24 12:40 UTC, wpf500 commented on src/pages/admin/settings/index.vue
> +                prefix="%"
`suffix` better than `prefix` ?

2024-04-24 16:11 UTC, JumpLink commented
> I think this PR doesn't add the tax rate to the join form right? Just the admin side?

Yes, I think the join part can be implemented together with new UX design, or should I add the tax also to the current to be able to ship this without the new join UX flow?

2024-04-25 14:54 UTC, wpf500 approved these changes

2024-05-10 08:28 UTC, merged